REGB_NONE   = 0x00
REGB_REGMASK= 0xF0
REGB_XAX    = 0x01<<4
REGB_XBX    = 0x02<<4
REGB_XCX    = 0x03<<4
REGB_XDX    = 0x04<<4
REGB_XSP    = 0x05<<4
REGB_XBP    = 0x06<<4
REGB_XSI    = 0x07<<4
REGB_XDI    = 0x08<<4

REGB_SIZEMASK= 0xE
REGB_32BIT   = 0x8
REGB_16BIT   = 0x4
REGB_8BIT    = 0x2

REGB_RLO = 0x0
REGB_RHI = 0x1

REG_MAP = {
	'':REGB_NONE, 
	'EAX':REGB_XAX|REGB_32BIT, 'AX':REGB_XAX|REGB_16BIT, 'AL':REGB_XAX|REGB_8BIT, 'AH':REGB_XAX|REGB_8BIT|REGB_RHI, 
	'EBX':REGB_XBX|REGB_32BIT, 'BX':REGB_XBX|REGB_16BIT, 'BL':REGB_XBX|REGB_8BIT, 'BH':REGB_XBX|REGB_8BIT|REGB_RHI, 
	'ECX':REGB_XCX|REGB_32BIT, 'CX':REGB_XCX|REGB_16BIT, 'CL':REGB_XCX|REGB_8BIT, 'CH':REGB_XCX|REGB_8BIT|REGB_RHI, 
	'EDX':REGB_XDX|REGB_32BIT, 'DX':REGB_XDX|REGB_16BIT, 'DL':REGB_XDX|REGB_8BIT, 'DH':REGB_XDX|REGB_8BIT|REGB_RHI, 
	'ESP':REGB_XSP|REGB_32BIT, 'SP':REGB_XSP|REGB_16BIT, 
	'EBP':REGB_XBP|REGB_32BIT, 'BP':REGB_XBP|REGB_16BIT, 
	'ESI':REGB_XSI|REGB_32BIT, 'SI':REGB_XSI|REGB_16BIT, 
	'EDI':REGB_XDI|REGB_32BIT, 'DI':REGB_XDI|REGB_16BIT
}

IMMREG_MAP = [
	[], 
	[REG_MAP['AL'], REG_MAP['CL'], REG_MAP['DL'], REG_MAP['BL'], REG_MAP['AH'], REG_MAP['CH'], REG_MAP['DH'], REG_MAP['BH']], 
	[REG_MAP['AX'], REG_MAP['CX'], REG_MAP['DX'], REG_MAP['BX'], REG_MAP['SP'], REG_MAP['BP'], REG_MAP['SI'], REG_MAP['DI']], 
	[], 
	[REG_MAP['EAX'], REG_MAP['ECX'], REG_MAP['EDX'], REG_MAP['EBX'], REG_MAP['ESP'], REG_MAP['EBP'], REG_MAP['ESI'], REG_MAP['EDI']]
]

REGSZ_MAP = {
	REGB_NONE : 0, 
	REGB_8BIT : 1, 
	REGB_16BIT: 2, 
	REGB_32BIT: 4
}

DATSZ_MAP = {
	'DWORD': 4, 
	'WORD' : 2, 
	'BYTE' : 1
}